pipeline {
    agent any

    environment {
        APP_DIR = "Py_model"
        DOCKER_IMAGE = "python-trivy-demo"
        IMAGE_NAME = "${DOCKER_IMAGE}:${BUILD_NUMBER}"
        TRIVY_CACHE_DIR = "${WORKSPACE}/.trivy_cache"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${APP_DIR}") {
                    sh "docker build -t ${IMAGE_NAME} ."
                }
            }
        }
        stage('login to dockerhub') {
            steps {
                sh 'docker login -u devagyarattan -p Devagya@123'
            }
        }
        stage('push image') {
            steps {
                sh 'docker push devagyarattan/python-trivy-demo:${BUILD_NUMBER}'
            }
        }
        stage('Trivy Image Scan') {
            steps {
                sh "mkdir -p ${TRIVY_CACHE_DIR} reports"

                dir("${APP_DIR}") {

                    sh """
                    trivy image \
                      --cache-dir ${TRIVY_CACHE_DIR} \
                      --format json \
                      --output ${WORKSPACE}/reports/trivy-image.json \
                      ${IMAGE_NAME}
                    """

                    sh """
                    trivy image \
                      --cache-dir ${TRIVY_CACHE_DIR} \
                      --format template \
                      --template @trivy/html.tpl \
                      --output ${WORKSPACE}/reports/trivy-image.html \
                      ${IMAGE_NAME}
                    """

                    sh """
                    trivy image \
                      --cache-dir ${TRIVY_CACHE_DIR} \
                      --format cyclonedx \
                      --output ${WORKSPACE}/reports/sbom.json \
                      ${IMAGE_NAME}
                    """
                }
            }
        }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'reports/*', fingerprint: true
        }
    }
}
